const hobbies = [
  "Knitting",
  "Sewing",
  "Chess",
  "Board games",
  "Watching movies",
  "Candle making",
  "Cooking",
  "Homebrewing wine or beer",
  "Cross stitch",
  "Magic",
  "Bowling",
  "Language learning",
  "Calligraphy",
  "Meditation",
  "Podcasting",
  "Singing",
  "Dancing",
  "Scrapbooking",
  "Blogging",
  "Carpentry",
  "Playing a musical instrument",
  "Jewellery making",
  "Dominoes",
  "Flower arranging",
  "Video gaming",
  "Home improvements/DIY",
  "Reading",
  "Nail art",
  "Indoor gardening - bonsai trees, miniature herb garden, pot plants",
  "Drawing",
  "Painting",
  "Colouring",
  "Astronomy",
  "Baking",
  "Card games",
  "Creative writing",
  "DJing",
  "Acting/drama",
  "Embroidery",
  "Furniture building",
  "Ice skating",
  "Swimming",
  "Jigsaw puzzles",
  "Journalling",
  "Karate",
  "Listening to music",
  "Model building",
  "Origami",
  "Photography",
  "Table tennis",
  "Squash",
  "Boxing",
  "Wrestling",
  "Darts",
  "Fencing",
  "Gymnastics",
  "Laser tag",
  "Mahjong",
  "Yoga",
  "Weight training",
  "Snooker",
  "Pool",
  "Collecting"
];

export default hobbies;
