const sex_actions = [
    "Engages in anal eroticism",
    "Practices BDSM activities",
    "Participates in Bukkake",
    "Performs cunnilingus",
    "Performs fellatio",
    "Engages in group sex",
    "Enjoys kissing",
    "Masturbates",
    "Engages in non-penetrative sex",
    "Practices oral eroticism",
    "Explores sexual roles",
    "Tries different sex positions",
    "Engages in sexual roleplay",
    "Participates in human sexual activity",
    "Tries different sex positions",
    "Engages in amplexus",
    "Has anal sex",
    "Engages in anilingus",
    "Practices ass to mouth",
    "Explores ayoni",
    "Engages in bareback (sexual act)",
    "Uses baseball metaphors for sex",
    "Practices bondage (BDSM)",
    "Participates in Bukkake",
    "Practices cock and ball torture",
    "Experiments with coitus reservatus",
    "Experiences consummation",
    "Engages in conventional sex",
    "Explores coprophilia",
    "Enjoys creampie (sexual act)",
    "Likes cum shots",
    "Performs cunnilingus",
    "Practices deep-throating",
    "Explores dianism",
    "Shares dick pics",
    "Participates in dogging (sexual slang)",
    "Experiments with dominance and submission",
    "Tries donkey punch",
    "Engages in double penetration",
    "Explores dry sex",
    "Practices edging (sexual practice)",
    "Experiments with Ekiben (sexual act)",
    "Experiments with erotic electrostimulation",
    "Enjoys erotic humiliation",
    "Experiments with erotic lactation",
    "Likes erotic spanking",
    "Engages in erotic talk",
    "Enjoys facesitting",
    "Likes facials (sexual act)",
    "Performs fellatio",
    "Engages in fingering (sexual act)",
    "Explores fisting",
    "Enjoys food play",
    "Likes footjobs",
    "Engages in foreplay",
    "Explores fornication",
    "Enjoys frot",
    "Participates in gang bang",
    "Explores gay sexual practices",
    "Engages in groping",
    "Performs handjob",
    "Leaves hickeys",
    "Experiments with hogging (sexual practice)",
    "Enjoys humiliation",
    "Engages in sexual intercourse",
    "Explores intercrural sex",
    "Practices irrumatio",
    "Enjoys kissing",
    "Explores klismaphilia",
    "Experiments with kunyaza",
    "Engages in lesbian sexual practices",
    "Enjoys lotion play",
    "Likes making out",
    "Experiments with mammary intercourse",
    "Masturbates",
    "Joins the mile high club",
    "Experiments with Nanpa",
    "Likes nipple stimulation",
    "Engages in non-penetrative sex",
    "Experiences Nyotaimori",
    "Practices oral sex",
    "Reaches orgasm",
    "Explores orgastic potency",
    "Likes pearl necklace (sexual act)",
    "Tries pegging (sexual practice)",
    "Does pelvic thrust",
    "Engages in penis fencing",
    "Experiments with phone sex",
    "Enjoys physical intimacy",
    "Explores pompoir",
    "Likes prostate massage",
    "Engages in pseudocopulation",
    "Experiments with public sex",
    "Likes pussy torture",
    "Goes for a quickie (sexual act)",
    "Enjoys rusty trombone",
    "Explores scrotal inflation",
    "Engages in seduction",
    "Experiments with sensation play",
    "Practices serosorting",
    "Explores sex magic",
    "Engages in sexual penetration",
    "Enjoys sexual roleplay",
    "Follows sexual script theory",
    "Experiments with sloppy seconds",
    "Likes small penis humiliation",
    "Tries soaking (sexual practice)",
    "Explores swaffelen",
    "Practices tantric sex",
    "Engages in Taoist sexual practices",
    "Likes teabagging",
    "Explores tribadism",
    "Tries urethral intercourse",
    "Experiments with urethral sounding",
    "Likes urolagnia",
    "Explores urophagia",
    "Engages in Venus Butterfly"
];

export default sex_actions;